### ISSUE TITLE
Error trying the example

### ISSUE THREAD

**Issue by petri** [SYSTAP/blazegraph-python#1]
I get the following error:

> Traceback (most recent call last):
>   File "query.py", line 6, in <module>
>     server.update('load file:///Users/petri/Code/koodaamo/offering/triples.n3')
>   File "/Users/petri/Code/koodaamo/offering/blazegraph-python/pymantic/sparql.py", line 198, in update
>     return _Update(self, sparql, **kwargs).execute()
>   File "/Users/petri/Code/koodaamo/offering/blazegraph-python/pymantic/sparql.py", line 90, in execute
>     raise SPARQLQueryException('%s: %s\nQuery: %s' % (response, content, self.sparql))
> pymantic.sparql.SPARQLQueryException: {'status': '301', 'content-length': '0', 'location': 'http://10.211.55.4:9999/blazegraph/sparql', 'server': 'Jetty(9.2.3.v20140905)'}:
> Query: load file:///Users/petri/Code/koodaamo/offering/triples.n3

The server is running on debian, the client code  here on OSX.

**Comment by beebs-systap** [comment]
@igor-kim  Do you mind taking a look at this one?

**Comment by igor-kim** [comment]
HTTP error code 301 redirects request to 'http://10.211.55.4:9999/blazegraph/sparql' instead of 'http://10.211.55.4:9999/bigdata/sparql', which was specified in the example. The endpoint path was changed, but example has not been updated until now.

Please, use updated code:

https://wiki.blazegraph.com/wiki/index.php/Client_Libraries#Quick_Start
